version: 0.2

phases:
  install:
    runtime-version:
      python: 3.8
    commands:
      - echo "installing venv"
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo "install dependencies"
      - python manage.py collectstatic --noinput
      - python manage.py migrate
  build:
    commands:
      - echo "building"
      - python manage.py test
  post_build:
    commands:
      - echo "post build phase"
      - echo Zipping the application...
      - zip -r django-app.zip .
      - echo Build completed on `date`

artifacts:
  files:
    - django-app.zip
    - appspec.yml
    - scripts/**
  discard-paths: yes

cache:
  paths:
    - /root/.cache/pip